spring.application.name=ai-java
server.port=8081

#API Key for Open AI
spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.chat.client.enabled=false
#API Key for Gemini Free Tier
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Disable OpenAI auto-config so it doesn't conflict
#spring.ai.openai.chat.enabled=false

# Ensure Gemini is enabled
spring.ai.google.genai.chat.enabled=true
